/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lista;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 * A lsita usada no projeto juntamente com sua explicação se encontram no final do código, linha 478. Seus métodos na classe ListaJogo
 * @author Endryo
 */
public class JogoDaMemoria extends javax.swing.JFrame {

    /**
     * Creates new form JogoDaMemoria
     */
    public JogoDaMemoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Carta1 = new javax.swing.JButton();
        Carta2 = new javax.swing.JButton();
        Carta3 = new javax.swing.JButton();
        Carta4 = new javax.swing.JButton();
        Carta5 = new javax.swing.JButton();
        Carta10 = new javax.swing.JButton();
        Carta9 = new javax.swing.JButton();
        Carta8 = new javax.swing.JButton();
        Carta7 = new javax.swing.JButton();
        Carta6 = new javax.swing.JButton();
        Play = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        Carta1.setBackground(new java.awt.Color(0, 255, 0));
        Carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista/jogo/CartasBaralho/Coringa (2).png"))); // NOI18N
        Carta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Carta1.setBorderPainted(false);
        Carta1.setContentAreaFilled(false);
        Carta1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Carta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta1ActionPerformed(evt);
            }
        });

        Carta2.setBackground(new java.awt.Color(0, 255, 0));
        Carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista/jogo/CartasBaralho/Coringa (2).png"))); // NOI18N
        Carta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Carta2.setBorderPainted(false);
        Carta2.setContentAreaFilled(false);
        Carta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta2ActionPerformed(evt);
            }
        });

        Carta3.setBackground(new java.awt.Color(0, 255, 0));
        Carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista/jogo/CartasBaralho/Coringa (2).png"))); // NOI18N
        Carta3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Carta3.setBorderPainted(false);
        Carta3.setContentAreaFilled(false);
        Carta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta3ActionPerformed(evt);
            }
        });

        Carta4.setBackground(new java.awt.Color(0, 255, 0));
        Carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista/jogo/CartasBaralho/Coringa (2).png"))); // NOI18N
        Carta4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Carta4.setBorderPainted(false);
        Carta4.setContentAreaFilled(false);
        Carta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta4ActionPerformed(evt);
            }
        });

        Carta5.setBackground(new java.awt.Color(0, 255, 0));
        Carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista/jogo/CartasBaralho/Coringa (2).png"))); // NOI18N
        Carta5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Carta5.setBorderPainted(false);
        Carta5.setContentAreaFilled(false);
        Carta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta5ActionPerformed(evt);
            }
        });

        Carta10.setBackground(new java.awt.Color(0, 255, 0));
        Carta10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista/jogo/CartasBaralho/Coringa (2).png"))); // NOI18N
        Carta10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Carta10.setBorderPainted(false);
        Carta10.setContentAreaFilled(false);
        Carta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta10ActionPerformed(evt);
            }
        });

        Carta9.setBackground(new java.awt.Color(0, 255, 0));
        Carta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista/jogo/CartasBaralho/Coringa (2).png"))); // NOI18N
        Carta9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Carta9.setBorderPainted(false);
        Carta9.setContentAreaFilled(false);
        Carta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta9ActionPerformed(evt);
            }
        });

        Carta8.setBackground(new java.awt.Color(0, 255, 0));
        Carta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista/jogo/CartasBaralho/Coringa (2).png"))); // NOI18N
        Carta8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Carta8.setBorderPainted(false);
        Carta8.setContentAreaFilled(false);
        Carta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta8ActionPerformed(evt);
            }
        });

        Carta7.setBackground(new java.awt.Color(0, 255, 0));
        Carta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista/jogo/CartasBaralho/Coringa (2).png"))); // NOI18N
        Carta7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Carta7.setBorderPainted(false);
        Carta7.setContentAreaFilled(false);
        Carta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta7ActionPerformed(evt);
            }
        });

        Carta6.setBackground(new java.awt.Color(0, 255, 0));
        Carta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista/jogo/CartasBaralho/Coringa (2).png"))); // NOI18N
        Carta6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Carta6.setBorderPainted(false);
        Carta6.setContentAreaFilled(false);
        Carta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta6ActionPerformed(evt);
            }
        });

        Play.setText("Play");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aperte Play para começar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Carta1)
                        .addGap(18, 18, 18)
                        .addComponent(Carta2)
                        .addGap(18, 18, 18)
                        .addComponent(Carta3)
                        .addGap(18, 18, 18)
                        .addComponent(Carta4)
                        .addGap(18, 18, 18)
                        .addComponent(Carta5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Carta6)
                        .addGap(18, 18, 18)
                        .addComponent(Carta7)
                        .addGap(18, 18, 18)
                        .addComponent(Carta8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Carta9)
                        .addGap(18, 18, 18)
                        .addComponent(Carta10)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Play)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carta5)
                    .addComponent(Carta2)
                    .addComponent(Carta1)
                    .addComponent(Carta3)
                    .addComponent(Carta4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carta10)
                    .addComponent(Carta7)
                    .addComponent(Carta6)
                    .addComponent(Carta8)
                    .addComponent(Carta9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(Play)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed

        this.Start(this.controle);

    }//GEN-LAST:event_PlayActionPerformed

    private void Carta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta1ActionPerformed
        if (this.Carta1.getBackground() != Color.GREEN && this.Carta1.getBackground() != Color.RED && controle == 1) {
            verificaCarta(0);
        }
    }//GEN-LAST:event_Carta1ActionPerformed

    private void Carta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta4ActionPerformed
        if (this.Carta4.getBackground() != Color.GREEN && this.Carta4.getBackground() != Color.RED && controle == 1) {
            verificaCarta(3);
        }
    }//GEN-LAST:event_Carta4ActionPerformed

    private void Carta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta2ActionPerformed
        if (this.Carta2.getBackground() != Color.GREEN && this.Carta2.getBackground() != Color.RED && controle == 1) {
            verificaCarta(1);
        }
    }//GEN-LAST:event_Carta2ActionPerformed

    private void Carta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta3ActionPerformed
        if (this.Carta3.getBackground() != Color.GREEN && this.Carta3.getBackground() != Color.RED && controle == 1) {
            verificaCarta(2);
        }
    }//GEN-LAST:event_Carta3ActionPerformed

    private void Carta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta5ActionPerformed
        if (this.Carta5.getBackground() != Color.GREEN && this.Carta5.getBackground() != Color.RED && controle == 1) {
            verificaCarta(4);
        }
    }//GEN-LAST:event_Carta5ActionPerformed

    private void Carta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta6ActionPerformed
        if (this.Carta6.getBackground() != Color.GREEN && this.Carta6.getBackground() != Color.RED && controle == 1) {
            verificaCarta(5);
        }
    }//GEN-LAST:event_Carta6ActionPerformed

    private void Carta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta7ActionPerformed
        if (this.Carta7.getBackground() != Color.GREEN && this.Carta7.getBackground() != Color.RED && controle == 1) {
            verificaCarta(6);
        }
    }//GEN-LAST:event_Carta7ActionPerformed

    private void Carta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta8ActionPerformed
        if (this.Carta8.getBackground() != Color.GREEN && this.Carta8.getBackground() != Color.RED && controle == 1) {
            verificaCarta(7);
        }
    }//GEN-LAST:event_Carta8ActionPerformed

    private void Carta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta9ActionPerformed
        if (this.Carta9.getBackground() != Color.GREEN && this.Carta9.getBackground() != Color.RED && controle == 1) {
            verificaCarta(8);
        }
    }//GEN-LAST:event_Carta9ActionPerformed

    private void Carta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta10ActionPerformed
        if (this.Carta10.getBackground() != Color.GREEN && this.Carta10.getBackground() != Color.RED && controle == 1) {
            verificaCarta(9);
        }
    }//GEN-LAST:event_Carta10ActionPerformed

    private void Start(int controle) {
        switch (controle) {
            case 0:
                this.setBotoes();
                this.tabuleiro.limpar();
                this.setSortCarta();
                for(int i =0; i < 10; i++){
                    botoes[i].setBackground(Color.GREEN);
                    botoes[i].setBorderPainted(false);
                }
                this.controle++;
                this.Escreve("Aperte o Play para esconder as cartas");
                break;
            case 1:
                for(int i =0; i < 10; i++){
                    this.imgCarta("Coringa", "2", botoes[i]);
                    botoes[i].setBackground(Color.BLACK);
                }
                this.Play.setEnabled(false);
                Sorteio();
                break;
        }
    }

    private void imgCarta(String naipe, String face, javax.swing.JButton botao) {

        ImageIcon imgCarta = new ImageIcon(getClass().getResource("/vetor/jogo/CartasBaralho/" + naipe + " (" + face + ").png"));
        imgCarta.setImage(imgCarta.getImage().getScaledInstance(167, 243, 1));
        (botao).setIcon(imgCarta);
        this.tabuleiro.insereValor(imgCarta);
    }

    private void setSortCarta() {
        for (int i = 0; i < 10; i++) {
            String[] nps = {"Ouro", "Copas", "Espadas", "Paus"};
            String[] fcs = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"};
            String naipe = nps[(int) (Math.random() * nps.length)];
            String face = fcs[(int) (Math.random() * fcs.length)];
            if (consultaElemento(naipe + face) == false) {
                this.imgCarta(naipe, face, botoes[i]);
                this.setSorteio(naipe, face, i);
                this.valores[i] = naipe + face;
            } else {
                i--;
            }

        }
    }

    public boolean consultaElemento(String valor) {
        for (int i = 0; i < this.valores.length; i++) {
            if (valor.equals(this.valores[i])) {
                return true;
            }
        }
        return false;
    }

    private void setBotoes() {
        botoes[0] = Carta1;
        botoes[1] = Carta2;
        botoes[2] = Carta3;
        botoes[3] = Carta4;
        botoes[4] = Carta5;
        botoes[5] = Carta6;
        botoes[6] = Carta7;
        botoes[7] = Carta8;
        botoes[8] = Carta9;
        botoes[9] = Carta10;
    }

    private void setSorteio(String naipe, String face, int pos) {
        this.naipes[pos] = naipe;
        this.faces[pos] = face;
    }

    private void Sorteio() {
        this.indice = (int) (Math.random() * 10);
        if (faces[indice] != null) {
            switch (Integer.parseInt(faces[indice])) {
                case 11:
                    Escreve("Encontre: Valete de " + naipes[indice]);
                    break;
                case 12:
                    Escreve("Encontre: Dama de " + naipes[indice]);
                    break;
                case 13:
                    Escreve("Encontre: Rei de " + naipes[indice]);
                    break;
                default:
                    Escreve("Encontre: " + faces[indice] + " de " + naipes[indice]);
                    break;
            }
        } else {
            Sorteio();
        }
    }

    private void verificaCarta(int pos) {
        this.contador++;
        if (tabuleiro.getValores(pos) == tabuleiro.getValores(indice)) {
            botoes[indice].setIcon(tabuleiro.getValores(indice));
            this.faces[indice] = null;
            botoes[indice].setBorder(javax.swing.BorderFactory.createLineBorder(Color.GREEN, 2));
            botoes[indice].setBorderPainted(true);
            botoes[pos].setBackground(Color.GREEN);
            this.pontos++;
            if(this.contador < 10){
                Sorteio();
            }else{
                this.Escreve("Parabéns! Você acertou: "+pontos+" Cartas (Aperte Play para jogar de novo)");
                this.Play.setEnabled(true);
                this.controle = 0;
                this.contador = 0;
                this.pontos = 0;
            }
        } else {
            botoes[pos].setIcon(tabuleiro.getValores(pos));
            this.faces[pos] = null;
            botoes[pos].setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED, 2));
            botoes[pos].setBorderPainted(true);
            botoes[pos].setBackground(Color.RED);
        }
    }

    private void Escreve(String texto) {
        this.jLabel1.setText(texto);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDaMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDaMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDaMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDaMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDaMemoria().setVisible(true);
            }
        });
    }
    private javax.swing.JButton[] botoes = new javax.swing.JButton[10];
    ListaJogo tabuleiro = new ListaJogo(10);//Lista de ImageIcon usada para receber as cartas sorteadas para o jogo. Seus métodos para consultar, adicionar e excluir estão na classe ListaJogo
    private String[] naipes = new String[10];
    private String[] valores = new String[10];
    private String[] faces = new String[10];
    private int indice;
    private int controle;
    private int contador;
    private int pontos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carta1;
    private javax.swing.JButton Carta10;
    private javax.swing.JButton Carta2;
    private javax.swing.JButton Carta3;
    private javax.swing.JButton Carta4;
    private javax.swing.JButton Carta5;
    private javax.swing.JButton Carta6;
    private javax.swing.JButton Carta7;
    private javax.swing.JButton Carta8;
    private javax.swing.JButton Carta9;
    private javax.swing.JButton Play;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
